// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestamosGHI.Data;

namespace PrestamosGHI.Data.Migrations
{
    [DbContext(typeof(PrestamosGHIContext))]
    [Migration("20200815102425_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrestamosGHI.Model.CalculoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("GuiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NroCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("Pendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrestamoGuiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestamoIdPrestamo")
                        .HasColumnType("int");

                    b.Property<decimal>("cuotaMensual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PrestamoIdPrestamo");

                    b.ToTable("CalculoLists");
                });

            modelBuilder.Entity("PrestamosGHI.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("AprobadaRechasada")
                        .HasColumnType("bit");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fprestamo")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IngresoNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPrestamo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Plazo")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PrestamosGHI.Model.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Concepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("PrestamosGHI.Model.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cuota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("IdPago");

                    b.HasIndex("PrestamoId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("PrestamosGHI.Model.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("FormaPago")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("Fpago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fprestamo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Plazo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<string>("guid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guidSolicitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("PrestamosGHI.Model.CalculoList", b =>
                {
                    b.HasOne("PrestamosGHI.Model.Cliente", null)
                        .WithMany("CalculoList")
                        .HasForeignKey("ClienteId");

                    b.HasOne("PrestamosGHI.Model.Prestamo", null)
                        .WithMany("CalculoList")
                        .HasForeignKey("PrestamoIdPrestamo");
                });

            modelBuilder.Entity("PrestamosGHI.Model.Gasto", b =>
                {
                    b.HasOne("PrestamosGHI.Model.Pago", null)
                        .WithOne("Gasto")
                        .HasForeignKey("PrestamosGHI.Model.Gasto", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrestamosGHI.Model.Pago", b =>
                {
                    b.HasOne("PrestamosGHI.Model.Prestamo", null)
                        .WithOne("Pago")
                        .HasForeignKey("PrestamosGHI.Model.Pago", "PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrestamosGHI.Model.Prestamo", b =>
                {
                    b.HasOne("PrestamosGHI.Model.Cliente", null)
                        .WithOne("Prestamo")
                        .HasForeignKey("PrestamosGHI.Model.Prestamo", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
